"""Add duration to Walk model

Revision ID: 3d706405f85c
Revises: 
Create Date: 2025-06-26 17:34:56.794916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d706405f85c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walk', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
