"""Add route column to Walk

Revision ID: 7aeb0c5eeb9a
Revises: 3d706405f85c
Create Date: 2025-07-01 00:50:29.312172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aeb0c5eeb9a'
down_revision = '3d706405f85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walk', schema=None) as batch_op:
        batch_op.drop_column('route')

    # ### end Alembic commands ###
